title: "Crux (ALCF)"

compute_node: balsam.platform.compute_node.CruxNode
mpi_app_launcher: balsam.platform.app_run.CruxRun
local_app_launcher: balsam.platform.app_run.LocalAppRun
mpirun_allows_node_packing: true

serial_mode_startup_params: 
    cpu_affinity: none

scheduler_class: balsam.platform.scheduler.PBSScheduler
allowed_queues:
    workq-route:
        max_nodes: 512
        max_queued_jobs: 20
        max_walltime: 1440

allowed_projects:
- datascience

optional_batch_job_params: {}
